export const base_Url = "https://app.jsonserver.io/server/7e86026e-427b-42a6-879e-e386de8b3c9c"
export const customer_url = "/customer"
export const order_url = "/orders"
export const food_url = "/food"
export const drink_url = "/drink"